### ISSUE TITLE
Choose templating engine

### ISSUE THREAD

**Issue by koppor** [latextemplates/generator-latex-template#1]
- [Jinja2](http://jinja.pocoo.org/) - recommended by @mfa, also because of http://eosrei.net/articles/2015/11/latex-templates-python-and-jinja2-generate-pdfs
- [Cheetah](http://cheetahtemplate.org/) - recommended at https://tex.stackexchange.com/q/41875/9075
- Apache Velocity - recommended by http://tex-talk.net/2012/03/generating-latex-code-with-a-template-engine/
- lualatex - recommended by @Stefan-Kottwitz at http://tex-talk.net/2012/03/generating-latex-code-with-a-template-engine/#comment-231

**Comment by miwurster** [comment]
Hey, what about [Yeoman](http://yeoman.io) as generator engine? 

There are also a couple of generators available for Latex:

* https://github.com/Andi-Lo/generator-latex
* https://github.com/LeoColomb/generator-latex

Cheers
Michael

**Comment by koppor** [comment]
@miwurster Thank you for the pointer. We finally use Yeoman! See https://github.com/latextemplates/generator-latex-template/blob/master/docs/adr/0001-use-yeoman.md.
