### ISSUE TITLE
.gitignore file missing when installing from npm

### ISSUE THREAD

**Issue by LyzardKing** [latextemplates/generator-latex-template#7]
Hi @koppor 
I tried installing as is described in the README, but I get this error when I run the generator:
`AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /home/galileo/.node_modules/lib/node_modules/generator-latex-template/generators/app/templates/.gitignore`

The file is actually missing..

**Comment by koppor** [comment]
Fixed in https://github.com/latextemplates/generator-latex-template/commit/e83a7ae735bba9fa1e7f3085a1850d3e40dab5ae. Please update to the latest version.
